<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="damload.classify.config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="FastEndpoints" Version="5.35.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DamLoad.Data\DamLoad.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Api\V1\Classifications\Endpoints\" />
  </ItemGroup>

</Project>
